Vagrant.configure("2") do |config|
  config.vm.box = "debian/testing64"
  config.disksize.size = '80GB'
  config.vm.hostname = "machine"
  # config.vm.network 'private_network', virtualbox__intnet: 'Security', type: 'dhcp'

  # config.vm.synced_folder "~/vm_shared_folders/temp", "/vagrant_temp", SharedFoldersEnableSymlinksCreate: false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  $apt = <<-SCRIPT
  wget http://http.kali.org/kali/pool/main/k/kali-archive-keyring/kali-archive-keyring_2022.1_all.deb
  dpkg -i kali-archive-keyring_2022.1_all.deb
  SCRIPT
  config.vm.provision 'shell', inline: $apt
  config.vm.provision :reload

  config.vm.provision 'shell', path: 'puppet.sh'

  # Disable installing Virtualbox tools
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.cpus = 2
    vb.name= "TST: Testing - Kali x64"
    vb.memory = "4096"
  end

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "init.pp"
    puppet.module_path = "modules"
    puppet.options = "--verbose --debug"
  end

end
